name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm install remark-cli remark-preset-lint-consistent

      - name: Run markdown lint
        run: |
          npx remark . --use remark-preset-lint-consistent --frail || true
          npx remark . --use remark-preset-lint-consistent --frail > remark-lint-report.json || true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-unique-artifact-name-1  # Altere para um nome único
          path: path/to/artifact



      - uses: actions/upload-artifact@v4
        with:
          name: remark-lint-report-json
          path: remark-lint-report.json
