name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm install remark-cli remark-preset-lint-consistent

      - name: Run markdown lint
        run: |
          npx remark . --use remark-preset-lint-consistent --frail || true
          npx remark . --use remark-preset-lint-consistent --frail > reports/remark-lint-report.json || true

      - name: Upload lint report artifact
        uses: actions/upload-artifact@v4
        with:
          name: remark-lint-report  # Nome único do artefato
          path: reports/remark-lint-report.json  # Caminho para o arquivo de relatório JSON

